# -*- coding: utf-8 -*-
"""ds_report.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1guZZ9M9a3PiR4ZBX8_jzNV4DtYw2D89F
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

trades = pd.read_csv("historical_data (1).csv")
print(trades.columns)

import pandas as pd

trades = pd.read_csv("historical_data (1).csv")
print(trades.columns)

trades['time'] = pd.to_datetime(trades['Timestamp'], unit='ms')
trades['date'] = trades['time'].dt.date

# Basic useful columns
trades['pnl'] = trades['Closed PnL']
trades['abs_size'] = trades['Size USD'].abs()
trades['direction'] = trades['Side'].map({'Buy': 'Long', 'Sell': 'Short'})
trades['win'] = (trades['pnl'] > 0).astype(int)

fear = pd.read_csv("fear_greed_index (1).csv")

fear['date'] = pd.to_datetime(fear['date']).dt.date
fear['sentiment'] = fear['classification'].map({
    'Fear': 0,
    'Greed': 1
})

fear.head()

fear['sentiment'] = fear['classification'].map({
    'Fear': 0,
    'Extreme Fear': 0,
    'Greed': 1,
    'Extreme Greed': 1
})

data = trades.merge(
    fear[['date', 'sentiment']],
    on='date',
    how='left'
)

data.head()

daily = (
    data
    .groupby(['Account','date','sentiment'])
    .agg(
        daily_pnl=('pnl','sum'),
        win_rate=('win','mean'),
        trades_per_day=('pnl','count'),
        avg_size=('abs_size','mean'),
        long_ratio=('direction', lambda x: (x=='Long').mean())
    )
    .reset_index()
)

daily.head()

daily.groupby('sentiment')[['daily_pnl','win_rate']].mean()

daily.groupby('sentiment')[[
    'trades_per_day',
    'avg_size',
    'long_ratio'
]].mean()

freq = daily['trades_per_day'].median()

daily['freq_type'] = daily['trades_per_day'].apply(
    lambda x: 'Frequent' if x > freq else 'Infrequent'
)

daily.groupby(['freq_type','sentiment'])['daily_pnl'].mean()

